#!/bin/bash
# Quick Supabase setup helper script

echo "🚀 AgentG Supabase Setup Helper"
echo "================================"
echo ""
echo "This script will help you set up Supabase for AgentG."
echo ""
echo "📋 Prerequisites:"
echo "   1. Supabase account (sign up at https://supabase.com)"
echo "   2. A Supabase project created"
echo "   3. Your database connection string"
echo ""
echo "📝 Steps to complete:"
echo ""
echo "1. Create Supabase project:"
echo "   → Go to https://supabase.com"
echo "   → Click 'New Project'"
echo "   → Fill in project details and create"
echo ""
echo "2. Get connection string:"
echo "   → Go to Settings → Database"
echo "   → Copy the 'URI' connection string"
echo "   → Replace [YOUR-PASSWORD] with your database password"
echo ""
echo "3. Run schema:"
echo "   → Go to SQL Editor in Supabase dashboard"
echo "   → Copy contents of shared/schema.sql"
echo "   → Paste and run in SQL Editor"
echo ""
echo "4. Update .env file:"
echo "   → Add DATABASE_URL with your Supabase connection string"
echo ""
echo "5. Test connection:"
echo "   → Run: python scripts/test_db_connection.py"
echo ""
echo "📖 For detailed instructions, see: SUPABASE_SETUP.md"
echo ""
echo "✅ Once you've completed these steps, your database will be ready!"

